export const suggestions = [
  'Al aire libre',
  'Argentina',
  'Aventura',
  'Bicicleta',
  'Brasil',
  'Buenos Aires',
  'Caminata',
  'Catamarca',
  'Chaco',
  'Chile',
  'Chubut',
  'Colombia',
  'Cordillera',
  'Cordoba',
  'Corrientes',
  'Escalar',
  'Entre Rios',
  'Extremo',
  'Formosa',
  'Glaciar',
  'Jujuy',
  'La Pampa',
  'La Rioja',
  'Mendoza',
  'Misiones',
  'Montaña',
  'Naturaleza',
  'Neuquen',
  'Paracaidismo',
  'Perito Moreno',
  'Rafting',
  '4x4',
  'Rio',
  'Rio Acequia',
  'Rio Negro',
  'Salta',
  'San Juan',
  'San Luís',
  'Santa Cruz',
  'Santa Fe',
  'Santiago del Estero',
  'Sierra',
  'Tierra del Fuego',
  'Tucuman',
  'Venezuela',
]